language: ruby
cache: bundler
rvm:
  - 2.7
  - 2.6
  - 2.5
  - 2.4
gemfile:
  - Gemfile
  - Gemfile.redis4
  - Gemfile.redis5
jobs:
  exclude:
    - rvm: 2.4
    - gemfile: Gemfile.redis5
script: bundle exec rspec
services:
  - redis-server
sudo: false
